# fly.toml app configuration file generated for arsen-discord-bot on 2023-09-27T12:13:18+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "arsen-discord-bot"
primary_region = "nrt"

[build]

[http_service]
  internal_port = 8080
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
